name: Publish to NPM
on:
  push:
    tags:
      - 'v*'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
          registry-url: https://registry.npmjs.org/
      - name: Run Test Cases
        run: |
          yarn
          yarn run lint --dry-run
          yarn run test:unit
      - name: Publish to NPM
        env:
          NPM_TOKEN: ${NPM_TOKEN}
        run: |
          npm publish --access public